### ISSUE TITLE
Voltron gdb issues on arch linux and displaying the source on lldb

### ISSUE THREAD

**Issue by edrickhong** [snare/voltron#133]
Hey, I really like what you done. Debugging might just become bearable now on unix platforms. Anyway, I would just like to report that using gdb, views cannot be connected anymore once I start executing the program. For example when running voltron view dis:

Encountered an exception while running the view 'DisasmView':
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/voltron/main.py", line 47, in main
    inst.run()
  File "/usr/lib/python2.7/site-packages/voltron/view.py", line 248, in run
    self.render()
  File "/usr/lib/python2.7/site-packages/voltron/plugins/view/disasm.py", line 28, in render
    res = self.client.send_request(req)
  File "/usr/lib/python2.7/site-packages/voltron/core.py", line 372, in send_request
    response = self.session.post(self.url, data=str(request))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/site-packages/voltron/view.py", line 344, in sigwinch_handler
    self.do_render()
  File "/usr/lib/python2.7/site-packages/voltron/view.py", line 324, in do_render
    self.fmt_body = self.body
AttributeError: 'DisasmView' object has no attribute 'body'

This seems to be the case with all the views so far. However, it works perfectly fine if I call the views before running the program in the debugger. I switched to lldb to use voltron and do not experience this issue. I just might use it there in the meantime. It seems to work better there anyway.

Speaking of lldb, how do I get a view of the source? I tried executing the command shown in the screenshot 'source list -a $rip' but I get this error instead:

Exception executing debugger command: Exception('error: unknown or ambiguous option',)

I typed this into lldb and it displayed the source just fine though.

And if it is any help, I am running on arch linux with gdb version 7.11-1 and lldb version 3.7.1-1.

**Comment by snare** [comment]
Hey,

Glad you like it :) re: your LLDB issue, you need to escape the $ in the register expression on the command line:

$ voltron view "source list -a \$rip" 

Or use single quotes, whatever. $rip is getting expanded as a shell variable.

Re: the GDB issue, I'll have to investigate. I only really test on Ubuntu x64.

**Comment by edrickhong** [comment]
Thanks. And idk if this helps but I checked the arch user repository and one of the comments said something about python 3.5 . It might be this? Then again the comment was made months ago. The link is here if you want to take a look: https://aur.archlinux.org/packages/voltron-git/ .

**Comment by snare** [comment]
Ah that guy made a PR which I rejected because it broke some stuff, and it looks like his Arch package is doing some of the stuff that was in his PR which won't work any more because I *did* end up moving `dbgentry.py` into the package as he suggested (and renaming it to `entry.py`).

I haven't tested on 3.5 specifically, but it does work on Ubuntu 14.04 with whatever 3.x is installed by default. I'll have to grab an arch ISO and give it a try.

**Comment by snare** [comment]
Can you try fe4e9990e54562779adfa947366d40dc7770001b?

I think something else is going on but that might just stop the error from occurring.

**Comment by snare** [comment]
The current source tree (including that last commit) works fine for me on Arch, can you try it?

**Comment by snare** [comment]
I'll try to run the tests on Arch in future as well (at least for releases).

**Comment by edrickhong** [comment]
I'll give it a try once I get home. Thanks for everything.
