### ISSUE TITLE
in MacOSX lldb with errors.

### ISSUE THREAD

**Issue by ahjkk** [snare/voltron#136]
when i  open lldb.
input 

command script import /.path/to/entry.py

and i also fixed /path/to/entry.py to my really path. 
it show errors with below:

(lldb) command script import /Library/Python/2.7/site-packages/voltron/entry.py
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/voltron/entry.py", line 43, in <module>
    import blessed
  File "build/bdist.macosx-10.6-intel/egg/blessed/__init__.py", line 10, in <module>
  File "build/bdist.macosx-10.6-intel/egg/blessed/terminal.py", line 10, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynloa

and i install python 3.5 and voltron ,then retry 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/voltron/entry.py", line 43, in <module>
    import blessed
  File "build/bdist.macosx-10.6-intel/egg/blessed/__init__.py", line 10, in <module>
  File "build/bdist.macosx-10.6-intel/egg/blessed/terminal.py", line 10, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

 but it still have errors.

how to resolve it?

**Comment by ahjkk** [comment]
oh.. i know what's problem with my question ... 
in lldb , i just test command script import one python scritpt with import blessed it still have errors.
so, mybe it's about the system path or some path 's question.
it tell me , in system i have a python context, when i open lldb it's another python context.
so ,i try to find a way to resolve it.

**Comment by ahjkk** [comment]
i finish it.

**Comment by snare** [comment]
I recently added some code to work around this issue. Please try the current version from the GitHub repo.
