### ISSUE TITLE
HTTPConnectionPool error

### ISSUE THREAD

**Issue by najeex** [snare/voltron#140]
**i am first time try voltron. this is very intrastion tool and went to use this tool but  this is the error show in terminal **
**voltron view reg **
`Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xb66be7cc>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.15.1-py3.4.egg/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: /api/request (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb66be7cc>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/voltron-0.1.2-py3.4.egg/voltron/view.py", line 233, in run
    self.server_version = self.client.perform_request('version')
  File "/usr/local/lib/python3.4/dist-packages/voltron-0.1.2-py3.4.egg/voltron/core.py", line 455, in perform_request
    res = self.send_request(req)
  File "/usr/local/lib/python3.4/dist-packages/voltron-0.1.2-py3.4.egg/voltron/core.py", line 385, in send_request
    response = self.session.post(self.url, data=str(request))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: /api/request (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb66be7cc>: Failed to establish a new connection: [Errno 111] Connection refused',))

                                                                                                                            
Error: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: /api/request (Caused by NewConnectio>

`

**Comment by snare** [comment]
Have you started the inferior in (I assume) GDB?

https://github.com/snare/voltron#bugs-and-errata

**Comment by najeex** [comment]
thanks sir .. no sir i am not started inferior in gdb. i google gdb inferior and try some command. but error still hare. sir can you help how i start.. i have no idea show i start...thanks

**Comment by najeex** [comment]
sir think voltron help to solve ctf challange  like RE and software explotitaion...now i am use radare2. r2 help not very much.i think voltron help me..

**Comment by snare** [comment]
You need to "run" the program you're debugging and step in the debugger before Voltron will connect and update.

Try [doing this](https://github.com/snare/voltron/wiki/Troubleshooting) and you'll see what I mean. Just use GDB instead of LLDB.

**Comment by najeex** [comment]
**sorry sir i don't get it....i am doing this way ....
**
`najeeb@najeeb:~/Music/ctf/PicoCTF-2013/overflow$ gdb -q overflow2-44e63640e033ff2b 
Voltron loaded.
Reading symbols from overflow2-44e63640e033ff2b...done.
   (gdb) run AAAAA
Starting program: /home/najeeb/Music/ctf/PicoCTF-2013/overflow/overflow2-44e63640e033ff2b AAAAA

win = 0
Sorry, you lose.
[Inferior 1 (process 5898) exited normally]
(gdb)`

**and in other terminal** 

`najeeb@najeeb:~$ voltron v r


Error: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded wi>


`

**Comment by snare** [comment]
Voltron updates its views whenever the debugger *stops*. Your debugger is never stopping. You need to set a breakpoint and for the debugger to hit it. Please do *exactly* as I said in the previous post and you will see, which you clearly have not done.

**Comment by snare** [comment]
Start your view in one terminal:

```
$ voltron v r
```

Then start the debugger, set a breakpoint and hit the breakpoint (using the test inferior included with Voltron):

```
$ gdb tests/inferior
(gdb) b main
(gdb) run
(gdb) stepi
```

The view will not be updated until the `stepi` instruction is run. This is clearly stated in the documentation.

**Comment by najeex** [comment]
thanks you very much sir it work.....

**Comment by snare** [comment]
No problem.
