### ISSUE TITLE
Not sure how to get the views

### ISSUE THREAD

**Issue by prokash** [snare/voltron#157]
I get this - ( on a osx terminal or iterm2 terminal) when on other terminal I've lldb running and stopped at a break point -

$ voltron view stack
Traceback (most recent call last):
  File "/usr/local/bin/voltron", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9.0'))

The other terminal has the following -
frame #0: 0x0000000100000cc8 a.out`main + 56 at strrchr.c:45
   42  	    char *tmp, *pch, *pfullpath;
   43  	
   44  	
-> 45  	     strcpy(fullpath, "test/bare/VM_10_9H/Users/Machintosh HD" );
   46  	     printf("fullpath=%s\n",fullpath);
   47  	     tmp = _strrchr(fullpath, '/');
   48  	     if (tmp) {

I would appreciate if some home gives me the steps to get a view like the one I see on the example section with several panes ( close to Ollydbg ).

TA,
P

**Comment by snare** [comment]
Looks like the `six` module hasn't updated. This has happened for me once but I'm not sure why. You should be able to fix it by telling pip to update it:

$ pip install six --upgrade

As for the panes, split the terminal horizontally/vertically in iTerm2 (cmd-D/cmd-shift-D) and lay them out how you like and run the views in them. You can also automate the layout with tmux: https://github.com/snare/voltron/wiki/Layout-automation <https://github.com/snare/voltron/wiki/Layout-automation>

**Comment by snare** [comment]
Or you might need to install `six` to your user dir if that doesn't work?

$ pip install six --user --upgrade

I'll investigate

**Comment by prokash** [comment]
Thanks much

**Comment by prokash** [comment]
Not sure where the problem is. I tried and it complained -
pip install six --upgrade
Collecting six
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/tv/qzqptw_x2bvc1p7r5k7nf54w0000gn/T/pip-mHYb4s-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

After that nothing changes. It does do the same thing as before …

**Comment by snare** [comment]
Did you try the `--user` version?

**Comment by prokash** [comment]
Thanks, that took care of it …
