### ISSUE TITLE
MacOSX lldb ERROR

### ISSUE THREAD

**Issue by handeslfy** [snare/voltron#178]
open lldb input 

command script import /.path/to/entry.py

An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/Library/Python/2.7/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/Library/Python/2.7/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/Library/Python/2.7/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 7, in <module>
    from six.moves.queue import Queue
ImportError: No module named queue

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation

//-----------------------------------------------------------------------------------

just input 'voltron'

Traceback (most recent call last):
  File "/usr/local/bin/voltron", line 9, in <module>
    load_entry_point('voltron==0.1.7', 'console_scripts', 'voltron')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/Library/Python/2.7/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/Users/cxf/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/Library/Python/2.7/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 7, in <module>
    from six.moves.queue import Queue
ImportError: No module named queue

wooooo.......help me

**Comment by snare** [comment]
Try this:

$ pip install six --user --upgrade

Some versions of OS X ship with an older version of the six module

**Comment by handeslfy** [comment]
My OSX is 11.6 ,so it is can't run.  I try updata to 12.1  voltron is run. 
so thank your ask fo me .
