### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by feicong** [snare/voltron#189]
macOS 10.11.6, run ./install.sh ok, but run lldb got an error:
`
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/Users/rmbp/git/voltron/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/Users/rmbp/git/voltron/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/Library/Python/2.7/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/Library/Python/2.7/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/Library/Python/2.7/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/Library/Python/2.7/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/Library/Python/2.7/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/Library/Python/2.7/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/Users/rmbp/git/voltron/voltron/plugins/debugger/dbg_gdb.py", line 7, in <module>
    from six.moves.queue import Queue
ImportError: No module named queue

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation
`

**Comment by snare** [comment]
You might need to update the `six` module. There's another open issue (#183) to add this to the install script.

`$ pip install six --user --upgrade --ignore-installed ` might do it

**Comment by feicong** [comment]
ok thx, resolved .
