### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by pzwwei** [snare/voltron#195]
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Users/pzwwei/Library/Python/2.7/lib/python/site-packages/voltron/entry.py", line 99, in <module>
    voltron.command = plugin.command_class(*args)
  File "/Users/pzwwei/.voltron/plugins/debugger/dbg_lldb.py", line 543, in __init__
    super(LLDBCommand, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by snare** [comment]
Did you manually copy `dbg_lldb.py` into `~/.voltron/plugins`?
