### ISSUE TITLE
nothing happe in cdb

### ISSUE THREAD

**Issue by mutepigz** [snare/voltron#238]
I use ConEmu to work it , but nothing happen.
```
0:000> .load pykd
0:000> !py --global C:\Users\random\Desktop\workplace\pykd\voltron\voltron\entry.py
Voltron loaded.
0:000> p
ntdll!LdrpDoDebuggerBreak+0x31:
00000000`7702cb61 eb00            jmp     ntdll!LdrpDoDebuggerBreak+0x33 (00000000`7702cb63)
0:000>
ntdll!LdrpDoDebuggerBreak+0x33:
00000000`7702cb63 4883c438        add     rsp,38h
```

**Comment by snare** [comment]
Are you opening views in other terminals?

**Comment by mutepigz** [comment]
yeah , i also used git bash, but nothing happend.

**Comment by snare** [comment]
What do you mean “nothing happened”? What do the views look like? Are you stepping in the debugger/hitting a breakpoint or something?

**Comment by mutepigz** [comment]
nothing happened means it's the same as the time when i haven't used voltron
```
0:000> .load pykd
0:000> !py --global C:\Users\random\Desktop\workplace\pykd\voltron\voltron\entry.py
Voltron loaded.
0:000> p
ntdll!LdrpDoDebuggerBreak+0x31:
00000000`7702cb61 eb00            jmp     ntdll!LdrpDoDebuggerBreak+0x33 (00000000`7702cb63)
0:000>
ntdll!LdrpDoDebuggerBreak+0x33:
00000000`7702cb63 4883c438        add     rsp,38h
```
there is no view and the color is still white.

**Comment by snare** [comment]
To be clear: nothing will happen *inside* the CDB console. Voltron is for attaching views in OTHER consoles to debuggers.

You need to open a new console git bash window and run:

$ voltron view reg

Or whatever. Read the documentation.

**Comment by mutepigz** [comment]
oh, thanx very much..
but new problem appear :
```
> voltron view stack

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\voltron-0.1.7-py2.7.egg\voltron\core.py", line 548, in run
    self.update()
  File "C:\Python27\lib\site-packages\voltron-0.1.7-py2.7.egg\voltron\core.py", line 511, in update
    reqs = self.build_requests()
  File "C:\Python27\lib\site-packages\voltron-0.1.7-py2.7.egg\voltron\plugins\view\memory.py", line 215, in build_requests
    return super(StackView, self).build_requests()
  File "C:\Python27\lib\site-packages\voltron-0.1.7-py2.7.egg\voltron\plugins\view\memory.py", line 46, in build_requests
    height, width = self.window_size()
  File "C:\Python27\lib\site-packages\voltron-0.1.7-py2.7.egg\voltron\view.py", line 310, in window_size
    height, width = subprocess.check_output(['stty', 'size']).split()
  File "C:\Python27\lib\subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]
```
