### ISSUE TITLE
Use of 'async' keywork causing syntax error

### ISSUE THREAD

**Issue by mtihlenfield** [snare/voltron#241]
As of python 3.7 `async` is a reserved keyword. It's use in `voltron/plugins/view/memory.py` line 16 causes a `SyntaxError` on systems that use python 3.7.  Here is an example starting gdb on Arch Linux:

```
$ gdb
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/home/strav/.local/lib/python3.7/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/home/strav/devel/voltron/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/home/strav/devel/voltron/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "/home/strav/devel/voltron/voltron/plugins/view/memory.py", line 16
    async = True
          ^
SyntaxError: invalid syntax

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation
```

It also happens just trying to run voltron on it's own like so:

```
$ voltron
Traceback (most recent call last):
  File "/usr/bin/voltron", line 11, in <module>
    load_entry_point('voltron==0.1.7', 'console_scripts', 'voltron')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/strav/devel/voltron/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/home/strav/devel/voltron/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/home/strav/.local/lib/python3.7/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "/home/strav/devel/voltron/voltron/plugins/view/memory.py", line 16
    async = True
          ^
SyntaxError: invalid syntax
```

This looks like a great tool! I look forward to being able to use it.

**Comment by ls69knight** [comment]
Open the file ""/home/strav/devel/voltron/voltron/plugins/view/memory.py"" and comment the line "async = True"

**Comment by zcutlip** [comment]
PR #243 should address this. Please open a new issue if the problem persists.

**Comment by rileyrg** [comment]
pip3 install voltron. same issue. debian 11.
