### ISSUE TITLE
error importing voltron

### ISSUE THREAD

**Issue by Mcimagamer** [snare/voltron#247]
`An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/home/user/.local/lib/python3.7/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/home/user/.local/lib/python3.7/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/home/user/.local/lib/python3.7/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/home/user/.local/lib/python3.7/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/home/user/.local/lib/python3.7/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/home/user/.local/lib/python3.7/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/home/user/.local/lib/python3.7/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "/home/user/.local/lib/python3.7/site-packages/voltron/plugins/view/memory.py", line 16
    async = True
          ^
SyntaxError: invalid syntax

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation`
I get this error when loading gdb, i got no errors during the install, and installed the packets for my current version, for version 3.0, and version 2.7 just to be sure. I'm using Manjaro.

**Comment by xurtis** [comment]
it appears that python 3.7 made `async` and `await` keywords.

https://docs.python.org/3/whatsnew/3.7.html
