### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by sterling0x1** [snare/voltron#250]
This is not a major issue, Voltron seems to run fine (after defeating issues where Voltron use user python instead of system install). when lldb loads Voltron this message come up and can't get my head around it.
weakref is seems to be ok tho, if I run a python shell and run "import weakref" I get no issues at all.

MacBook-Pro:~ sterling$ lldb
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Voltron loaded.

**Comment by snare** [comment]
Looks like you're importing Voltron out of a home-brew Python site-packages, or you have a brew python ahead of system python in PYTHONPATH or something. LLDB is linked against the system python and Voltron must be installed into the system python's site-packages (or a user site-packages for the system Python).

**Comment by sterling0x1** [comment]
right, removing brew install kinda fixed it.
For some reason on first install, Voltron didn't see my python install, so I installed via brew, I reckon that caused the issue.
Thanks for assisting :)
