### ISSUE TITLE
Voltron uninstall

### ISSUE THREAD

**Issue by alegs1** [snare/voltron#253]
When I try to uninstall Voltron in Mac0s 10.14.2, I get following error for this command
/usr/bin/python -m pip uninstall voltron
bash-3.2$ /usr/bin/python -m pip uninstall voltron
Uninstalling voltron-0.1.7:
  Would remove:
    /Library/Python/2.7/site-packages/voltron-0.1.7-py2.7.egg-info
    /Library/Python/2.7/site-packages/voltron/*
    /usr/local/bin/voltron
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  _File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/commands/uninstall.py", line 75, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/req/req_install.py", line 683, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/req/req_uninstall.py", line 224, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/utils/misc.py", line 280, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/voltron-0.1.7-py2.7.egg-info/PKG-INFO'_

**Comment by cydave** [comment]
Try sudo, you seem to have installed it into the global python library path. As evident by the permission denied error.

**Comment by zcutlip** [comment]
Yep use sudo, and open a new issue if that doesn't work Closing this for now.
