### ISSUE TITLE
voltron crashing on start when being installed using pip with Python 3.7

### ISSUE THREAD

**Issue by fdik** [snare/voltron#263]
`% voltron
Traceback (most recent call last):
  File "/Users/vb/Library/Python/3.7/bin/voltron", line 5, in <module>
    from voltron import main
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/scruffy/env.py", line 49, in __init__
    self.add(**kwargs)
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/scruffy/env.py", line 114, in add
    self._children[key].prepare()
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/scruffy/file.py", line 439, in prepare
    self.load()
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/scruffy/file.py", line 445, in load
    self._pm.load_plugins(self.path)
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "/Users/vb/Library/Python/3.7/lib/python/site-packages/voltron/plugins/view/memory.py", line 16
    async = True
          ^
SyntaxError: invalid syntax`

**Comment by lanza** [comment]
async is a python3 keyword. Just change the variable name.

**Comment by cydave** [comment]
For reference 09d1d75b4d158faef17c8aca22f258c60157550a

**Comment by dwizzzle** [comment]
Any idea why @cydave commit is not included in the pip3 install?  I just hit the same issue

**Comment by cydave** [comment]
@dwizzzle  My best guess would be that the release on Pypi is out of date.
