### ISSUE TITLE
ImportError on "DispatcherMiddleware" with werkzeug 1.0.1

### ISSUE THREAD

**Issue by SuperStormer** [snare/voltron#278]
Running any `voltron` command returns this error.
```python
Traceback (most recent call last):
  File "/home/user/.local/bin/voltron", line 5, in <module>
    from voltron import main
  File "/home/user/.local/lib/python3.8/site-packages/voltron/__init__.py", line 6, in <module>
    from .main import main
  File "/home/user/.local/lib/python3.8/site-packages/voltron/main.py", line 9, in <module>
    from .view import *
  File "/home/user/.local/lib/python3.8/site-packages/voltron/view.py", line 25, in <module>
    from .core import Client
  File "/home/user/.local/lib/python3.8/site-packages/voltron/core.py", line 18, in <module>
    from werkzeug.wsgi import DispatcherMiddleware, SharedDataMiddleware
ImportError: cannot import name 'DispatcherMiddleware' from 'werkzeug.wsgi' (/home/user/.local/lib/python3.8/site-packages/werkzeug/wsgi.py)
```
This is caused by `DispatcherMiddleware` moving to `werkzeug.middleware.dispatcher.DispatcherMiddleware`.

**Comment by SuperStormer** [comment]
Fixed issue by installing from github; manual install docs and pypi package are both outdated though.
