### ISSUE TITLE
mac python2.7报错；饿

### ISSUE THREAD

**Issue by liumengdeqq** [snare/voltron#282]
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 49, in __init__
    self.add(**kwargs)
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 114, in add
    self._children[key].prepare()
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 439, in prepare
    self.load()
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 445, in load
    self._pm.load_plugins(self.path)
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/Users/liumeng/Library/Python/2.7/lib/python/site-packages/voltron/plugins/debugger/dbg_lldb.py", line 579
    log.warning(f"Exception when saving hook index for unregistering. {e}")
                                                                         ^
SyntaxError: invalid syntax

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation

**Comment by duraki** [comment]
@zcutlip this happens as well on my fresh install

```
# ~ tried latest tag && master
galaxy@devil. voltron 776a84c ∙ python -V
Python 2.7.16

galaxy@devil. voltron 776a84c ∙ lldb
(lldb) command script import /Users/hduraki/Library/Python/2.7/lib/python/site-packages/voltron/entry.py
WARNING: Python 2.7 is not recommended. Future versions of lldb will not support Python 2.7.
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 49, in __init__
    self.add(**kwargs)
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/scruffy/env.py", line 114, in add
    self._children[key].prepare()
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 439, in prepare
    self.load()
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/scruffy/file.py", line 445, in load
    self._pm.load_plugins(self.path)
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/Users/hduraki/Library/Python/2.7/lib/python/site-packages/voltron/plugins/debugger/dbg_lldb.py", line 579
    log.warning(f"Exception when saving hook index for unregistering. {e}")
                                                                         ^
SyntaxError: invalid syntax

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation
```

Installed via `./install.sh`
