### ISSUE TITLE
Mac M1: ImportError: dlopen... symbol not found in flat namespace '_PyInt_FromSsize_t

### ISSUE THREAD

**Issue by Niebelungen-D** [snare/voltron#292]
I get this error when loading Voltron in lldb and this also occurred when I install Voltron by Home-brew python3.9
```bash
error: module importing failed: Traceback (most recent call last):
  File "/System/Volumes/Data/Users/niebelungen/Library/Python/2.7/lib/python/site-packages/voltron/entry.py", line 39, in <module>
    import logging
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
ImportError: dlopen(/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cStringIO.so, 0x0002): symbol not found in flat namespace '_PyInt_FromSsize_t'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Volumes/Data/Users/niebelungen/Library/Python/2.7/lib/python/site-packages/voltron/entry.py", line 117, in <module>
    if blessed:
NameError: name 'blessed' is not defined
``` 
I found that voltron seems to change the python environment of lldb to python2.7. 
I'd like to know how to fix it. How should I properly install voltron？

**Comment by Niebelungen-D** [comment]
I change `DefaultPythonVersion` to 3. and use Home-brew python3.9 to install Voltron. Then commit this section of code in `entry.py`
```python
#try:
    # fix path if it's clobbered by brew
#    import sys
#    if sys.platform == 'darwin':
#        py_base = '/System/Library/Frameworks/Python.framework/Versions/2.7/'
#        new_path = ['lib/python27.zip', 'lib/python2.7', 'lib/python2.7/plat-darwin', 'lib/python2.7/plat-mac',
#                    'lib/python2.7/plat-mac/lib-scriptpackages', 'Extras/lib/python', 'lib/python2.7/lib-tk',
#                    'lib/python2.7/lib-old', 'lib/python2.7/lib-dynload']
#        sys.path = [p for p in sys.path if 'Cellar' not in p] + [py_base + p for p in new_path]
#except:
#    pass
```
It works finally.

**Comment by MstMoonshine** [comment]
I ran into the same problem. Where is the `DefaultPythonVersion` variable located?

**Comment by Niebelungen-D** [comment]
> I ran into the same problem. Where is the `DefaultPythonVersion` variable located?

just run this in your terminal.
```
defaults write com.apple.dt.lldb DefaultPythonVersion 3
```
