### ISSUE TITLE
Can't run on OSX 10.9 (ImportError: No module named lldb)

### ISSUE THREAD

**Issue by vstepanyuk** [snare/voltron#41]
[vitaliy:~] $ voltron
Traceback (most recent call last):
  File "/usr/local/bin/voltron", line 9, in <module>
    load_entry_point('voltron==0.1', 'console_scripts', 'voltron')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 2108, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/**init**.py", line 8, in <module>
    from .main import *
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/main.py", line 15, in <module>
    from .console import *
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/console.py", line 6, in <module>
    import lldb
ImportError: No module named lldb

**Comment by revolter** [comment]
`export PYTHONPATH=$PYTHONPATH:/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python` in your `.bashrc`/`.zshrc`/... for newbies like me.
