### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_success'

### ISSUE THREAD

**Issue by mcourteaux** [snare/voltron#73]
Running `voltron view stack` with `lldb` gives me:

	Encountered an exception while running the view 'StackView':
	Traceback (most recent call last):
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/main.py", line 49, in main
	    inst.run()
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/view.py", line 215, in run
	    self.render()
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/view/memory.py", line 153, in render
	    super(StackView, self).render()
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/view/memory.py", line 85, in render
	    if deref_res.is_success:
	AttributeError: 'NoneType' object has no attribute 'is_success'

This triggers as soon as I step.

**Comment by snare** [comment]
Can you set `debug_logging` in the `general` section of your config, and there'll be a `~/.voltron/voltron_debugger.log` generated. See if there are any errors in there.

If you don't have a customised config, just put the following into `~/.voltron/config`:

```
{
    "general": {
        "debug_logging": true
    }
}
```

**Comment by snare** [comment]
Also, does this happen with every executable?

**Comment by mcourteaux** [comment]
Yes, it also happens with the OS X calculator. There are some errors in voltron_main:

	015-02-21 16:52:46,279 ERROR        core.py:419          send_request -- Exception parsing message:
	2015-02-21 16:52:46,279 ERROR        core.py:420          send_request -- Invalid message: {"status": "success", "data": {"output": [["pointer", 4298211648], ["pointer", 140735179593640], ["pointer", 140735179593680], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["pointer", 140735215210776], ["poin
	2015-02-21 16:52:46,280 ERROR        main.py:51                   main -- Exception running module StackView: Traceback (most recent call last):
	[ here comes the same error as the original post ]

I cut of the line with all the "pointer" occurences. It goes on like that for thousands of times. It actually ends like this: `35215210776], ["poin`. So I guess command is getting to long (and dump) and a buffer gets full, which causes the string to stop abruptly. (Also note the times from the errors, so the crash is caused by the corrupt super long request).

This comes out of voltron_debugger:

	015-02-21 16:52:44,105 ERROR   dereference.py:35               dispatch -- Exception executing debugger command: list index out of range
	2015-02-21 16:52:44,105 DEBUG        core.py:154      dispatch_request -- Response: {"status": "error", "data": {"message": "Exception executing debugger command: list index out of range", "code": 4096}, "type": "response"}
	2015-02-21 16:52:44,105 DEBUG        core.py:158      dispatch_request -- Client was passed to dispatch_request() - sending response
	2015-02-21 16:52:44,105 DEBUG        core.py:516         send_response -- Sending response server -> client: {"status": "error", "data": {"message": "Exception executing debugger command: list index out of range", "code": 4096}, "type": "response"}
	2015-02-21 16:52:44,106 DEBUG        core.py:508          recv_request -- Received request client -> server: {"request": "dereference", "type": "request", "data": {"pointer": 504411980245764102}}

And repeats several times (so you have all lines surrounding the ERROR line).

**Comment by mcourteaux** [comment]
Also, this is my python version: 

    Python 2.7.8 (default, Feb 21 2015, 16:38:04)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin

**Comment by snare** [comment]
Would you mind trying again with the latest commit? It should actually log the tracebacks now (I suck).

**Comment by mcourteaux** [comment]
Do I simply run `python setup.py install` to make these changes happen where needed, after pulling?

**Comment by snare** [comment]
Yep

**Comment by mcourteaux** [comment]
Yes, indeed there are tracebacks now: 

From voltron_debugger:

		2015-02-21 17:26:27,887 ERROR   dereference.py:35               dispatch -- Exception dereferencing pointer: list index out of range
	Traceback (most recent call last):
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/api/dereference.py", line 27, in dispatch
	    output = voltron.debugger.dereference(self.pointer)
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/dbg.py", line 52, in inner
	    return func(self, *args, **kwargs)
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/dbg.py", line 27, in inner
	    return func(self, *args, **kwargs)
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/dbg.py", line 67, in inner
	    raise e
	IndexError: list index out of range
	2015-02-21 17:26:27,888 DEBUG        core.py:154      dispatch_request -- Response: {"status": "error", "data": {"message": "Exception dereferencing pointer: list index out of range", "code": 4096}, "type": "response"}
	2015-02-21 17:26:27,888 DEBUG        core.py:158      dispatch_request -- Client was passed to dispatch_request() - sending response
	2015-02-21 17:26:27,888 DEBUG        core.py:516         send_response -- Sending response server -> client: {"status": "error", "data": {"message": "Exception dereferencing pointer: list index out of range", "code": 4096}, "type": "response"}
	2015-02-21 17:26:27,889 DEBUG        core.py:508          recv_request -- Received request client -> server: {"request": "dereference", "type": "request", "data": {"pointer": 504411980245764102}}
	2015-02-21 17:26:27,889 DEBUG        core.py:136      dispatch_request -- Dispatching request: {"request": "dereference", "type": "request", "data": {"pointer": 504411980245764102}}

From voltron_main:

	2015-02-21 17:26:30,193 ERROR        core.py:419          send_request -- Exception parsing message:
	Traceback (most recent call last):
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/core.py", line 404, in send_request
	    generic_response = APIResponse(data=data)
	  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/api.py", line 143, in __init__
	    raise InvalidMessageException()
	InvalidMessageException

And all the way at the bottom of voltron_main (just before it comes the huge request error where the seemingly infinite json request comes):

  2015-02-21 17:26:30,194 ERROR        main.py:51                   main -- Exception running module StackView: Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/main.py", line 49, in main
      inst.run()
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/view.py", line 215, in run
      self.render()
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/view/memory.py", line 153, in render
      super(StackView, self).render()
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/view/memory.py", line 85, in render
      if deref_res.is_success:
  AttributeError: 'NoneType' object has no attribute 'is_success'
  Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/main.py", line 49, in main
      inst.run()
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/view.py", line 215, in run
      self.render()
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/view/memory.py", line 153, in render
      super(StackView, self).render()
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1-py2.7.egg/voltron/plugins/view/memory.py", line 85, in render
      if deref_res.is_success:
  AttributeError: 'NoneType' object has no attribute 'is_success'

PS: I removed the logs before I restarted.

**Comment by snare** [comment]
OK, can you try the latest commit (624e01cf2c40f5cf557181e93a8db20f1a1c9df5)?

I thought I fixed this before :\

**Comment by mcourteaux** [comment]
Brilliant it works! Thanks a lot! :D

**Comment by snare** [comment]
Awesome :D
