### ISSUE TITLE
Linux socket connect error

### ISSUE THREAD

**Issue by huawenyu** [snare/voltron#97]
OS: Linux Mint 17.2
voltron version: git clone today.
```Shell
$ voltron view backtrace
Encountered an exception while running the view 'BacktraceView':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/main.py", line 53, in main
    inst.run()
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/view.py", line 228, in run
    self.server_version = self.client.perform_request('version')
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/core.py", line 407, in perform_request
    res = self.send_request(req)
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/core.py", line 337, in send_request
    response = self.session.post(self.url, data=str(request))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'http+unix://%2fhome%2fwilson%2f.voltron%2fsock/api/request'
```

**Comment by snare** [comment]
`requests_unixsocket` doesn’t seem to work on Linux. Add the following to your config to connect via TCP:

```
view:
	 api_url: http://localhost:5555/api/request
```

**Comment by defau1t** [comment]
Another note: If it shows up with "Connection refused", you have to actually run the inferior process and hit a breakpoint before it'll populate the views.

And if your Voltron views show "Connection reset by peer" or something like that after you've had a view successfully populate, running "voltron stopped" will reload the views.

Hope this helps!

**Comment by snare** [comment]
Yeah the server is only started and stopped with the inferior due to GDB hanging if you leave a socket open on exit. I'll see if I can make this a bit neater.
